name: visualize_dea
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=4.5.1
  - conda-forge::r-pheatmap=1.0.13
  - conda-forge::r-ggplot2=4.0.3
  - conda-forge::r-ggrepel=0.9.8
  - conda-forge::r-readr=2.2.0
  - conda-forge::r-dplyr=1.2.1
  - bioconda::bioconductor-deseq2=1.50.2